---
title: "Nuclear Consumption"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
Data <- read.csv(file.choose(),header = TRUE)
View(Data)

library(dplyr)
dde1= Data %>% select(country,year,population,gdp,nuclear_electricity,nuclear_cons_change_twh,nuclear_share_elec,nuclear_share_energy,nuclear_consumption) %>% filter(country == "United States" & year >= 1985 & year <=2018)
View(dde1)
summary(dde1)
str(dde1)
dde <- dde1[,-1:-2] #removed both Country and year column

normalize <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}

dde_norm <- as.data.frame(lapply(dde, normalize))
dde_norm <- cbind(dde1[,2],dde_norm)
colnames(dde_norm)[1]<-("year")
summary(dde_norm)
View(dde_norm)


set.seed(1234)
ind <- sample(2, nrow(dde_norm), replace = T, prob = c(0.7, 0.3))
dde_train <- dde_norm[ind == 1,]
dde_test <- dde_norm[ind == 2,]


str(dde_test)
View(dde_test)
View(dde_train[,-1])

# training a model on the above data
library(neuralnet)



dde_model <- neuralnet(nuclear_consumption~., data = dde_train[,-1])
dde_model


# model results
model_results <- compute(dde_model,dde_test[,-8])
model_results 
(predicted_cons <- model_results$net.result)
cor(dde_test$nuclear_consumption, predicted_cons)

VALIDATION=table(dde_test[,8],predicted_cons)
(ACCURACY=sum(diag(VALIDATION))/sum(VALIDATION)*100)
data_mod <- data.frame(Year = dde_test[,1],Predicted = predicted_cons,
                       Actual = dde_test[,6])
View(data_mod)
library(ggplot2)
library(plotly)
percentages <- round(predicted_cons / sum(predicted_cons) * 100)
data <- data.frame(dde_test[,1],percentages)
View(data)
```

# United States

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}
Bar<-ggplot(data_mod, aes(Year)) +  
  geom_line(aes(y = Actual, color = "Actual"),size = 1.5) +
  geom_line(aes(y = Predicted,color = "Predicted"),size = 1.5)+
  scale_color_manual(values = c("Actual" = "red", "Predicted" = "blue"))+
  scale_x_continuous(breaks = seq(1994, 2018, by = 4)) +
  xlab("Year") +
  ylab("Values") +
  ggtitle("Actual vs Predicted Values")
ggplotly(Bar)

```

Column {data-width=500}
-----------------------------------------------------------------------


### Chart B

```{r}
ggplot(data, aes(x = "", y = percentages, fill = as.factor(dde_test[,1]))) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  theme_void() +
  theme(legend.position = "right",plot.title = element_text(size = 16, face = "bold", color = "violet",hjust = 0.5)) +
  geom_text(aes(label = paste(percentages, "%")), position = position_stack(vjust = 0.5)) +
  scale_fill_discrete(name = "Year") + 
  labs(title = "Year-wise Predicted Values")
```

